name: shiny-deseq2-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.2  # Use an R version compatible with DESeq2 and shiny
  - r-shiny
  - r-dt
  - r-rcolorbrewer
  - r-heatmaply
  - r-shinythemes
  - r-shinyjs
  - r-plotly
  - bioconductor-deseq2
  - r-ggplot2

