name: deseq2-shiny
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3
  - bioconductor-deseq2>=1.40
  - r-shiny>=1.8
  - r-shinyjs
  - r-shinythemes
  - r-dt
  - r-plotly
  - r-ggplot2
  - r-heatmaply
  - r-pheatmap
  - r-rmarkdown
  - r-testthat
  - pandoc
